---
- name: testing group variables
  hosts: servers
  tasks:
   - name: create db {{dbname}}
     yum:
      name: httpd
      state: present
     become: yes
   - include: tasks/db.yml
   - include: tasks/db.yml
